name:                bell-triangle
version:             0.1.0.0
github:              "EmilGedda/bell-triangle"
license:             BSD3
author:              "Emil Gedda"
maintainer:          "emil.gedda@emilgedda.se"
copyright:           "2019 Emil Gedda"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EmilGedda/bell-triangle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bell-triangle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bell-triangle
    - pretty-simple >= 2.2 && < 3

tests:
  bell-triangle-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bell-triangle
